        /*Example post 01 reaction menu script*/
        $(document).ready(function(){
            $("#highest_reaction_postID_01").click(function(){
                $("#reactMenuContainer_postID_01").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#flag_postID_01").click(function(){
                $("#flagMenu_postID_01").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#verify_postID_01").click(function(){
                $("#verifyMenu_postID_01").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#emote_postID_01").click(function(){
                $("#emoteMenu_postID_01").slideToggle("fast");
            });
        });
        /*Example post 02 reaction menu script*/
        $(document).ready(function(){
            $("#highest_reaction_postID_02").click(function(){
                $("#reactMenuContainer_postID_02").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#flag_postID_02").click(function(){
                $("#flagMenu_postID_02").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#verify_postID_02").click(function(){
                $("#verifyMenu_postID_02").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#emote_postID_02").click(function(){
                $("#emoteMenu_postID_02").slideToggle("fast");
            });
        });
        /*Example post 03 reaction menu script*/
        $(document).ready(function(){
            $("#highest_reaction_postID_03").click(function(){
                $("#reactMenuContainer_postID_03").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#flag_postID_03").click(function(){
                $("#flagMenu_postID_03").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#verify_postID_03").click(function(){
                $("#verifyMenu_postID_03").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#emote_postID_03").click(function(){
                $("#emoteMenu_postID_03").slideToggle("fast");
            });
        });
        /*Example post 04 reaction menu script*/
        $(document).ready(function(){
            $("#highest_reaction_postID_04").click(function(){
                $("#reactMenuContainer_postID_04").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#flag_postID_04").click(function(){
                $("#flagMenu_postID_04").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#verify_postID_04").click(function(){
                $("#verifyMenu_postID_04").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#emote_postID_04").click(function(){
                $("#emoteMenu_postID_04").slideToggle("fast");
            });
        });
        /*Example post 05 reaction menu script*/
        $(document).ready(function(){
            $("#highest_reaction_postID_05").click(function(){
                $("#reactMenuContainer_postID_05").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#flag_postID_05").click(function(){
                $("#flagMenu_postID_05").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#verify_postID_05").click(function(){
                $("#verifyMenu_postID_05").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#emote_postID_05").click(function(){
                $("#emoteMenu_postID_05").slideToggle("fast");
            });
        });
        /*Example post 06 reaction menu script*/
        $(document).ready(function(){
            $("#highest_reaction_postID_06").click(function(){
                $("#reactMenuContainer_postID_06").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#flag_postID_06").click(function(){
                $("#flagMenu_postID_06").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#verify_postID_06").click(function(){
                $("#verifyMenu_postID_06").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#emote_postID_06").click(function(){
                $("#emoteMenu_postID_06").slideToggle("fast");
            });
        });
        /*Example post 07 reaction menu script*/
        $(document).ready(function(){
            $("#highest_reaction_postID_07").click(function(){
                $("#reactMenuContainer_postID_07").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#flag_postID_07").click(function(){
                $("#flagMenu_postID_07").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#verify_postID_07").click(function(){
                $("#verifyMenu_postID_07").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#emote_postID_07").click(function(){
                $("#emoteMenu_postID_07").slideToggle("fast");
            });
        });
        /*Example post 08 reaction menu script*/
        $(document).ready(function(){
            $("#highest_reaction_postID_08").click(function(){
                $("#reactMenuContainer_postID_08").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#flag_postID_08").click(function(){
                $("#flagMenu_postID_08").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#verify_postID_08").click(function(){
                $("#verifyMenu_postID_08").slideToggle("fast");
            });
        });
        $(document).ready(function(){
            $("#emote_postID_08").click(function(){
                $("#emoteMenu_postID_08").slideToggle("fast");
            });
        });


        $(document).ready(function(){
            $("#artistProfilePreview_postID_01").hover(function(){
                $("#featuredPostsPreview_postID_01").slideToggle("slow");
            });
        });
        $(document).ready(function(){
            $("#artistProfilePreview_postID_02").hover(function(){
                $("#featuredPostsPreview_postID_02").slideToggle("slow");
            });
        });
        $(document).ready(function(){
            $("#artistProfilePreview_postID_03").hover(function(){
                $("#featuredPostsPreview_postID_03").slideToggle("slow");
            });
        });